[book]
authors = ["minecraft-linux"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial *NIX Lancher for Minecraft"

[output.html]
git-repository-url = "https://github.com/minecraft-linux/minecraft-linux.github.io"
